# Generated by Django 4.0.4 on 2022-04-14 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_module_card'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'Модуль'},
        ),
        migrations.RemoveField(
            model_name='module',
            name='author',
        ),
    ]
