# Generated by Django 4.0.4 on 2022-04-20 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_module_options_module_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.module'),
        ),
    ]
