# Generated by Django 4.0.4 on 2022-04-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_question_description_delete_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='description',
        ),
        migrations.RemoveField(
            model_name='test',
            name='good',
        ),
        migrations.RemoveField(
            model_name='test',
            name='perfect',
        ),
        migrations.RemoveField(
            model_name='test',
            name='questions_count',
        ),
        migrations.RemoveField(
            model_name='test',
            name='satisfactorily',
        ),
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
